name: My Workflow

on:
  push:
    branches: [main]

jobs:
  main:
    env:  
      API_TOKEN: ${{ secrets.api_token }}
    runs-on: ubuntu-latest  
    steps:
      - name: Use secret 
        uses: ./.github/actions/getToken
