name: My Workflow

on:
  push:
    branches: [main]

jobs:
  main:
    env:  
      API_TOKEN: ${{ secrets.api_token }}
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Use secret 
        uses: ./.github/actions/my-action